apiVersion: v1
kind: Namespace
metadata:
  name: pi-system
  labels:
    app: controllerpi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: pi-system
  name: controllerpi
  labels:
    app: controllerpi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pi-system:controller
  labels:
    app: controllerpi
rules:
- apiGroups: [""]
  resources: ["services","nodes","pods", "deployments"]
  verbs: ["get", "list", "watch", "update", "delete"]
- apiGroups: [""]
  resources: ["services/status"]
  verbs: ["update"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: pi-system
  name: controller
  labels:
    app: controllerpi
rules:
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
## Role bindings
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pi-system:controller
  labels:
    app: controllerpi
subjects:
- kind: ServiceAccount
  name: controllerpi
  namespace: pi-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pi-system:controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: pi-system
  name: controller
  labels:
    app: controllerpi
subjects:
- kind: ServiceAccount
  name: controllerpi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pi-system
  name: controllerpi
spec:
  selector:
    matchLabels:
      app: controllerpi
  replicas: 1
  template:
    metadata:
      labels:
        app: controllerpi
    spec:
      serviceAccountName: controllerpi
      containers:
      - name: controller
        image: amioranza/controllerpi:v0
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: controllerpi
  namespace: pi-system
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 32185
  selector:
    app: controllerpi
